export const routes = {
  HOME: '/',
  CREATE: '/create',
  HOW_IT_WORKS: '/how-it-works',
  BLOG: '/blog',
  BLOG_ID: (id: string) => `/blog/${id}`,
  REQUEST_ID: (id: string) => `/request/${id}`,
  PROPOSAL_ID: (id: string) => `/proposal/${id}`,
  PROFILE: '/profile',
  PROFILE_BY_ID: (id: string) => `/profile/${id}`,
  LOGIN: '/login',
  REGISTER: '/register',
  PRICING: '/pricing',
  ABOUT: '/about',
  CONTACT: '/contact',
  TERMS: '/terms',
  PRIVACY: '/privacy',
  SUPPORT: '/support',
  REQUEST: '/request',
  PROPOSAL: '/proposal',
  ADMIN: '/admin',
} as const;
